"""create status column in ImportOrder table

Revision ID: 08f1f89cf696
Revises: d0a12ece1866
Create Date: 2024-04-19 19:59:14.989541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f1f89cf696'
down_revision: Union[str, None] = 'd0a12ece1866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_order', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_order', 'status')
    # ### end Alembic commands ###
