"""add product_name to noti

Revision ID: 0b81e49039a7
Revises: 3c4cc236a1e8
Create Date: 2024-04-22 16:04:36.786660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b81e49039a7'
down_revision: Union[str, None] = '3c4cc236a1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noti', sa.Column('product_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noti', 'product_name')
    # ### end Alembic commands ###
