"""change full_name type in employee table

Revision ID: 0bafdf4c4a47
Revises: d7fb39555ae7
Create Date: 2024-03-10 11:50:34.956381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bafdf4c4a47'
down_revision: Union[str, None] = 'd7fb39555ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_employee_name', 'employee', ['full_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_name', 'employee', type_='unique')
    # ### end Alembic commands ###
