"""Set timezone VN.

Revision ID: 0bb10bf46906
Revises: 7e6cc26e5393
Create Date: 2024-04-10 18:51:43.791703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb10bf46906'
down_revision: Union[str, None] = '7e6cc26e5393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
