"""change type manager_id to array

Revision ID: 0cce901e0790
Revises: e0398207ce57
Create Date: 2024-03-10 12:50:09.842686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cce901e0790'
down_revision: Union[str, None] = 'e0398207ce57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_branch_manager_name'), 'branch', ['manager_name'])
    op.drop_constraint('uq_employee_name', 'employee', type_='unique')
    op.create_unique_constraint(op.f('uq_employee_full_name'), 'employee', ['full_name'])
    op.drop_constraint('unique_system_settings_id', 'system_settings', type_='unique')
    op.create_unique_constraint(op.f('uq_system_settings_id'), 'system_settings', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_system_settings_id'), 'system_settings', type_='unique')
    op.create_unique_constraint('unique_system_settings_id', 'system_settings', ['id'])
    op.drop_constraint(op.f('uq_employee_full_name'), 'employee', type_='unique')
    op.create_unique_constraint('uq_employee_name', 'employee', ['full_name'])
    op.drop_constraint(op.f('uq_branch_manager_name'), 'branch', type_='unique')
    # ### end Alembic commands ###
