"""new table inventory check

Revision ID: 1198a7076ce2
Revises: ebf702fd0786
Create Date: 2024-05-11 17:53:22.676202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1198a7076ce2'
down_revision: Union[str, None] = 'ebf702fd0786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_check',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('branch_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('real_quantity', sa.Integer(), nullable=True),
    sa.Column('quantiry_in_db', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_check'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_check')
    # ### end Alembic commands ###
