"""Create change type in Product table

Revision ID: 150098dddaec
Revises: a37a3c8a51c2
Create Date: 2024-03-14 21:01:12.989375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '150098dddaec'
down_revision: Union[str, None] = 'a37a3c8a51c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'barcode',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product', 'unit',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product', 'last_purchase_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'has_promotion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
