"""create note column in ImportOrder

Revision ID: 15cc87dab15f
Revises: da9e5f7d1e67
Create Date: 2024-04-26 17:01:02.501454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cc87dab15f'
down_revision: Union[str, None] = 'da9e5f7d1e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_order', sa.Column('note', sa.String(), nullable=True))
    op.drop_column('import_order', 'promotion')
    op.drop_column('import_order', 'subtotal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_order', sa.Column('subtotal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('import_order', sa.Column('promotion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('import_order', 'note')
    # ### end Alembic commands ###
