"""change column name in inventory check table

Revision ID: 18f0d49bf56d
Revises: 7f158c8b7a63
Create Date: 2024-05-13 17:35:58.612689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f0d49bf56d'
down_revision: Union[str, None] = '7f158c8b7a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_check_detail', sa.Column('quantity_in_db', sa.Integer(), nullable=True))
    op.drop_column('inventory_check_detail', 'quantiry_in_db')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_check_detail', sa.Column('quantiry_in_db', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('inventory_check_detail', 'quantity_in_db')
    # ### end Alembic commands ###
