"""Create new column in purchase order.

Revision ID: 1909d29e97c3
Revises: fe66f9a9cfcc
Create Date: 2024-04-13 14:11:21.077159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1909d29e97c3'
down_revision: Union[str, None] = 'fe66f9a9cfcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoice_for_customer_belong_to_order', 'invoice_for_customer', type_='unique')
    op.drop_constraint('fk_invoice_for_customer_purchase_order', 'invoice_for_customer', type_='foreignkey')
    op.drop_column('invoice_for_customer', 'belong_to_order')
    op.add_column('purchase_order', sa.Column('invoice_id', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_purchase_order_invoice_id'), 'purchase_order', ['invoice_id'])
    op.create_foreign_key(op.f('fk_purchase_order_invoice_id_invoice_for_customer'), 'purchase_order', 'invoice_for_customer', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_purchase_order_invoice_id_invoice_for_customer'), 'purchase_order', type_='foreignkey')
    op.drop_constraint(op.f('uq_purchase_order_invoice_id'), 'purchase_order', type_='unique')
    op.drop_column('purchase_order', 'invoice_id')
    op.add_column('invoice_for_customer', sa.Column('belong_to_order', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_invoice_for_customer_purchase_order', 'invoice_for_customer', 'purchase_order', ['belong_to_order'], ['id'])
    op.create_unique_constraint('uq_invoice_for_customer_belong_to_order', 'invoice_for_customer', ['belong_to_order'])
    # ### end Alembic commands ###
