"""change vendor_name to unique = True

Revision ID: 1c7eecb26fd7
Revises: 27bd4f38f1e5
Create Date: 2024-05-08 22:51:27.170663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7eecb26fd7'
down_revision: Union[str, None] = '27bd4f38f1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_vendor_vendor_name'), 'vendor', ['vendor_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_vendor_vendor_name'), 'vendor', type_='unique')
    # ### end Alembic commands ###
