"""Add expiry_date column in ImportOrder

Revision ID: 1faf9a0b0ab8
Revises: 15df23dfbf2f
Create Date: 2024-04-24 20:11:24.840587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1faf9a0b0ab8'
down_revision: Union[str, None] = '15df23dfbf2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_order', sa.Column('expiry_date', sa.Date(), nullable=True))
    # op.drop_column('noti', 'branch')
    # op.drop_column('noti', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('noti', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('noti', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('import_order', 'expiry_date')
    # ### end Alembic commands ###
