"""add pdf_url to contract

Revision ID: 217e458f5e45
Revises: 6bca34369bd3
Create Date: 2024-05-02 16:07:39.195139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217e458f5e45'
down_revision: Union[str, None] = '6bca34369bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_for_vendor', sa.Column('pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_for_vendor', 'pdf_url')
    # ### end Alembic commands ###
