"""add column in contract

Revision ID: 27bd4f38f1e5
Revises: a16049c9a720
Create Date: 2024-05-08 11:57:19.000156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bd4f38f1e5'
down_revision: Union[str, None] = 'a16049c9a720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_for_vendor', sa.Column('latest_import', sa.Date(), nullable=True))
    op.add_column('contract_for_vendor', sa.Column('next_import', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_for_vendor', 'next_import')
    op.drop_column('contract_for_vendor', 'latest_import')
    # ### end Alembic commands ###
