"""is_contract nullable in ImportOrder

Revision ID: 2dae1cc6c7d1
Revises: 8900e1cfaef4
Create Date: 2024-04-21 01:23:34.554707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dae1cc6c7d1'
down_revision: Union[str, None] = '8900e1cfaef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_order', 'is_contract',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_order', 'is_contract',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
