"""Add promotion for categories table

Revision ID: 2eaabc8004f9
Revises: 818410fbef37
Create Date: 2024-03-01 11:24:53.287130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eaabc8004f9'
down_revision: Union[str, None] = '818410fbef37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_for_categories',
    sa.Column('promotion_code', sa.String(length=20), nullable=False),
    sa.Column('categories_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['categories_name'], ['categories.name'], ),
    sa.ForeignKeyConstraint(['promotion_code'], ['promotion.promotion_code'], ),
    sa.PrimaryKeyConstraint('promotion_code', 'categories_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotion_for_categories')
    # ### end Alembic commands ###
