"""delete constrain unique name categories

Revision ID: 33c2421e7eb4
Revises: d34c0bb0519a
Create Date: 2024-04-30 21:07:19.497302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c2421e7eb4'
down_revision: Union[str, None] = 'd34c0bb0519a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_categories_name', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_categories_name', 'categories', ['name'])
    # ### end Alembic commands ###
