"""Add FK to Contract table

Revision ID: 3fd627d05cff
Revises: 95d1e77b5cc1
Create Date: 2024-03-01 11:42:50.835716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd627d05cff'
down_revision: Union[str, None] = '95d1e77b5cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('belong_to_vendor', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'contract', 'vendor', ['belong_to_vendor'], ['vendor_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'belong_to_vendor')
    # ### end Alembic commands ###
