"""update table

Revision ID: 467d64a0397b
Revises: bdfdfdbf133e
Create Date: 2024-05-11 22:55:49.459100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467d64a0397b'
down_revision: Union[str, None] = 'bdfdfdbf133e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_check', sa.Column('branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_check', 'branch')
    # ### end Alembic commands ###
