"""drop invoice_id column

Revision ID: 4968a695743f
Revises: 1909d29e97c3
Create Date: 2024-04-15 10:37:24.074839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4968a695743f'
down_revision: Union[str, None] = '1909d29e97c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_purchase_order_invoice_id', 'purchase_order', type_='unique')
    op.drop_constraint('fk_purchase_order_invoice_id_invoice_for_customer', 'purchase_order', type_='foreignkey')
    op.drop_column('purchase_order', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('invoice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_purchase_order_invoice_id_invoice_for_customer', 'purchase_order', 'invoice_for_customer', ['invoice_id'], ['id'])
    op.create_unique_constraint('uq_purchase_order_invoice_id', 'purchase_order', ['invoice_id'])
    # ### end Alembic commands ###
