"""add img_url to product table

Revision ID: 49fd9ad874e7
Revises: d05f03033f0d
Create Date: 2024-05-02 14:25:32.850265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fd9ad874e7'
down_revision: Union[str, None] = 'd05f03033f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'img_url')
    op.add_column('product', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'img_url')
    op.add_column('employee', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
