"""Add column of model branch

Revision ID: 4c8633fd6ad5
Revises: a64834960092
Create Date: 2024-02-29 18:12:42.514985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8633fd6ad5'
down_revision: Union[str, None] = 'a64834960092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('name_display', sa.String(length=255), nullable=False))
    op.add_column('branch', sa.Column('name_detail', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'branch', ['name_detail'])
    op.drop_column('branch', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'branch', type_='unique')
    op.drop_column('branch', 'name_detail')
    op.drop_column('branch', 'name_display')
    # ### end Alembic commands ###
