"""increase len in Batch table

Revision ID: 520c8cfdd91f
Revises: 618f11180941
Create Date: 2024-04-20 15:44:54.593893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520c8cfdd91f'
down_revision: Union[str, None] = '618f11180941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch', 'belong_to_branch',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('batch', 'belong_to_receipt',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch', 'belong_to_receipt',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('batch', 'belong_to_branch',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
