"""change strlen belong_to_contract

Revision ID: 55a65c96f485
Revises: 33f5e6f09d88
Create Date: 2024-04-19 23:22:21.722548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a65c96f485'
down_revision: Union[str, None] = '33f5e6f09d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_order', 'belong_to_vendor',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('import_order', 'belong_to_contract',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_order', 'belong_to_contract',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('import_order', 'belong_to_vendor',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
