"""Change type of categories.id

Revision ID: 5719c2c39124
Revises: 71c6f9178ade
Create Date: 2024-03-14 09:44:03.549629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5719c2c39124'
down_revision: Union[str, None] = '71c6f9178ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('fk_employee_branch', 'employee', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_employee_branch', 'employee', 'branch', ['branch_name'], ['name_detail'])
    # ### end Alembic commands ###
