"""Set timezone VN.

Revision ID: 5d79b17db460
Revises: 1c2cc1eca7cd
Create Date: 2024-04-10 18:47:24.180972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d79b17db460'
down_revision: Union[str, None] = '1c2cc1eca7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
