"""Set timezone VN.

Revision ID: 5ddead027d9b
Revises: 0bb10bf46906
Create Date: 2024-04-10 20:09:16.532655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddead027d9b'
down_revision: Union[str, None] = '0bb10bf46906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('batch', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('branch_employees', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('branch_employees', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('contract_for_product', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('contract_for_product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('contract_for_vendor', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('contract_for_vendor', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('customer', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('customer', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('employee', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('employee', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('import_order', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('import_order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_order', 'updated_at')
    op.drop_column('import_order', 'created_at')
    op.drop_column('employee', 'updated_at')
    op.drop_column('employee', 'created_at')
    op.drop_column('customer', 'updated_at')
    op.drop_column('customer', 'created_at')
    op.drop_column('contract_for_vendor', 'updated_at')
    op.drop_column('contract_for_vendor', 'created_at')
    op.drop_column('contract_for_product', 'updated_at')
    op.drop_column('contract_for_product', 'created_at')
    op.drop_column('branch_employees', 'updated_at')
    op.drop_column('branch_employees', 'created_at')
    op.drop_column('batch', 'updated_at')
    op.drop_column('batch', 'created_at')
    # ### end Alembic commands ###
