"""create belong_to_branch without FK

Revision ID: 618f11180941
Revises: a569a18d06d3
Create Date: 2024-04-20 14:42:23.335835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618f11180941'
down_revision: Union[str, None] = 'a569a18d06d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_batch_belong_to_branch_branch', 'batch', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_batch_belong_to_branch_branch', 'batch', 'branch', ['belong_to_branch'], ['id'])
    # ### end Alembic commands ###
