"""Create table branch_employee.

Revision ID: 66fc6512c48c
Revises: 93d87b59afca
Create Date: 2024-04-10 16:16:53.009859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fc6512c48c'
down_revision: Union[str, None] = '93d87b59afca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_branch_manager_id', 'branch', type_='unique')
    op.drop_constraint('fk_branch_manager_id_employee', 'branch', type_='foreignkey')
    op.drop_column('branch', 'manager_id')
    op.drop_column('branch', 'manager_name')
    op.drop_column('employee', 'branch_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('branch_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('branch', sa.Column('manager_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('branch', sa.Column('manager_id', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_branch_manager_id_employee', 'branch', 'employee', ['manager_id'], ['id'])
    op.create_unique_constraint('uq_branch_manager_id', 'branch', ['manager_id'])
    # ### end Alembic commands ###
