"""Test.

Revision ID: 68445cbc21a0
Revises: f9ed6c48f919
Create Date: 2024-04-08 15:21:18.964598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68445cbc21a0'
down_revision: Union[str, None] = 'f9ed6c48f919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('test', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_account')),
    sa.UniqueConstraint('branch_name', name=op.f('uq_branch_account_branch_name')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_branch_account_phone_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch_account')
    # ### end Alembic commands ###
