"""add contract_id to noti

Revision ID: 6bca34369bd3
Revises: 352eb8e3b1e0
Create Date: 2024-05-02 15:59:49.221992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bca34369bd3'
down_revision: Union[str, None] = '352eb8e3b1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noti', sa.Column('contract_id', sa.String(), nullable=True))
    op.alter_column('noti', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('noti', 'batch_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('noti', 'batch_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('noti', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('noti', 'contract_id')
    # ### end Alembic commands ###
