"""Update constrain field vendor.

Revision ID: 6c838ea9ab1a
Revises: ab8bda6152f1
Create Date: 2024-04-03 15:52:21.460424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c838ea9ab1a'
down_revision: Union[str, None] = 'ab8bda6152f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
