"""add column to contract

Revision ID: 6da8843d5a2a
Revises: 49fd9ad874e7
Create Date: 2024-05-02 15:15:34.516457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da8843d5a2a'
down_revision: Union[str, None] = '49fd9ad874e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_for_vendor', sa.Column('latest_import', sa.String(), nullable=True))
    op.add_column('contract_for_vendor', sa.Column('next_import', sa.String(), nullable=True))
    op.add_column('contract_for_vendor', sa.Column('period', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_for_vendor', 'period')
    op.drop_column('contract_for_vendor', 'next_import')
    op.drop_column('contract_for_vendor', 'latest_import')
    # ### end Alembic commands ###
