"""create sub_total column in ImportOrder

Revision ID: 6fcc1ad4f79f
Revises: 15cc87dab15f
Create Date: 2024-04-26 17:04:44.727034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcc1ad4f79f'
down_revision: Union[str, None] = '15cc87dab15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_detail', sa.Column('sub_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_detail', 'sub_total')
    # ### end Alembic commands ###
