"""create branch column in categories table.

Revision ID: 7800cb538a04
Revises: b5dbc33d0159
Create Date: 2024-04-19 16:18:57.617010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7800cb538a04'
down_revision: Union[str, None] = 'b5dbc33d0159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('branch', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'branch')
    # ### end Alembic commands ###
