"""create new table

Revision ID: 7f158c8b7a63
Revises: 37c76a6524bb
Create Date: 2024-05-13 16:26:02.824087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f158c8b7a63'
down_revision: Union[str, None] = '37c76a6524bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('list_detail_id', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_check'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_check')
    # ### end Alembic commands ###
