"""Add tenant_id column in info table

Revision ID: 84579f64da37
Revises: de9100515200
Create Date: 2024-06-01 18:37:18.476829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84579f64da37'
down_revision: Union[str, None] = 'de9100515200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('info', sa.Column('tenant_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'tenant_id')
    op.drop_column('info', 'branch')
    # ### end Alembic commands ###
