"""Modify manager_name of branch constrain.

Revision ID: 87a160f79965
Revises: fa8d17b37e57
Create Date: 2024-03-30 17:19:28.942718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a160f79965'
down_revision: Union[str, None] = 'fa8d17b37e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_branch_manager_name', 'branch', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_branch_manager_name', 'branch', ['manager_name'])
    # ### end Alembic commands ###
