"""delete delivery status column in ImportOrder

Revision ID: 8900e1cfaef4
Revises: 96459ddae547
Create Date: 2024-04-21 01:18:06.558457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8900e1cfaef4'
down_revision: Union[str, None] = '96459ddae547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_order', 'delivery_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_order', sa.Column('delivery_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
