"""add column manager id to branch.

Revision ID: 8a10ba0df0b0
Revises: f351efe01652
Create Date: 2024-04-17 17:43:16.357414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a10ba0df0b0'
down_revision: Union[str, None] = 'f351efe01652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('manager_id', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_branch_manager_id'), 'branch', ['manager_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_branch_manager_id'), 'branch', type_='unique')
    op.drop_column('branch', 'manager_id')
    # ### end Alembic commands ###
