"""Add created_at, updated_at to invoice.

Revision ID: 8baf3f8fffb1
Revises: ca7c997240c8
Create Date: 2024-04-10 20:36:12.097495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8baf3f8fffb1'
down_revision: Union[str, None] = 'ca7c997240c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_for_customer', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('invoice_for_customer', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_for_customer', 'updated_at')
    op.drop_column('invoice_for_customer', 'created_at')
    # ### end Alembic commands ###
