"""estimated_date is nullable in import_order

Revision ID: 8fac744ec61b
Revises: 7800cb538a04
Create Date: 2024-04-19 16:48:15.727150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fac744ec61b'
down_revision: Union[str, None] = '7800cb538a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_order', 'estimated_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_order', 'estimated_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
