"""drop column

Revision ID: 92e2f16be9c8
Revises: 1198a7076ce2
Create Date: 2024-05-11 22:12:00.795918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e2f16be9c8'
down_revision: Union[str, None] = '1198a7076ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_check', sa.Column('id_', sa.Integer(), nullable=False))
    op.drop_column('inventory_check', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_check', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('inventory_check', 'id_')
    # ### end Alembic commands ###
