"""Add contraint unique to vendor table

Revision ID: 95d1e77b5cc1
Revises: c6cf12d917d7
Create Date: 2024-03-01 11:41:37.176015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d1e77b5cc1'
down_revision: Union[str, None] = 'c6cf12d917d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vendor', ['vendor_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor', type_='unique')
    # ### end Alembic commands ###
