"""add hashed pass column.

Revision ID: 99bad9cc11c2
Revises: 4968a695743f
Create Date: 2024-04-16 17:44:56.392899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bad9cc11c2'
down_revision: Union[str, None] = '4968a695743f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('branch', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('branch_employees', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('categories', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('contract_for_product', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('contract_for_vendor', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('customer', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('employee', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('employee', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('import_order', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('invoice_for_customer', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('invoice_from_vendor', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('order', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('order_of_batch', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('product', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('product_of_import_order', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('promotion', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('promotion_belong_to_branch', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('promotion_for_order', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('purchase_order', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('vendor', sa.Column('tenant_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'tenant_id')
    op.drop_column('purchase_order', 'tenant_id')
    op.drop_column('promotion_for_order', 'tenant_id')
    op.drop_column('promotion_belong_to_branch', 'tenant_id')
    op.drop_column('promotion', 'tenant_id')
    op.drop_column('product_of_import_order', 'tenant_id')
    op.drop_column('product', 'tenant_id')
    op.drop_column('order_of_batch', 'tenant_id')
    op.drop_column('order', 'tenant_id')
    op.drop_column('invoice_from_vendor', 'tenant_id')
    op.drop_column('invoice_for_customer', 'tenant_id')
    op.drop_column('import_order', 'tenant_id')
    op.drop_column('employee', 'tenant_id')
    op.drop_column('employee', 'hashed_password')
    op.drop_column('customer', 'tenant_id')
    op.drop_column('contract_for_vendor', 'tenant_id')
    op.drop_column('contract_for_product', 'tenant_id')
    op.drop_column('categories', 'tenant_id')
    op.drop_column('branch_employees', 'tenant_id')
    op.drop_column('branch', 'tenant_id')
    op.drop_column('batch', 'tenant_id')
    # ### end Alembic commands ###
