"""Update model user.

Revision ID: 9b75878ac538
Revises: 900b95eadf4e
Create Date: 2024-04-05 10:56:37.827201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b75878ac538'
down_revision: Union[str, None] = '900b95eadf4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
