"""delete column employee in branch.

Revision ID: 9d28a8f0ded9
Revises: 2ee386970d5d
Create Date: 2024-04-17 16:18:20.724828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d28a8f0ded9'
down_revision: Union[str, None] = '2ee386970d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
