"""drop column in contract

Revision ID: a16049c9a720
Revises: 217e458f5e45
Create Date: 2024-05-08 11:56:37.821246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16049c9a720'
down_revision: Union[str, None] = '217e458f5e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_for_vendor', 'next_import')
    op.drop_column('contract_for_vendor', 'latest_import')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_for_vendor', sa.Column('latest_import', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contract_for_vendor', sa.Column('next_import', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
