"""create branch column in import_order

Revision ID: a2e0f88d0c87
Revises: 520c8cfdd91f
Create Date: 2024-04-20 16:23:29.211747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e0f88d0c87'
down_revision: Union[str, None] = '520c8cfdd91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_order', sa.Column('branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_order', 'branch')
    # ### end Alembic commands ###
