"""create branch column in ImportDetail

Revision ID: a569a18d06d3
Revises: 20b1929d61b8
Create Date: 2024-04-20 14:06:24.227638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a569a18d06d3'
down_revision: Union[str, None] = '20b1929d61b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_detail', sa.Column('branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_detail', 'branch')
    # ### end Alembic commands ###
