"""create (order detail in invoice).

Revision ID: a5f2581af324
Revises: f09dfb4ab21c
Create Date: 2024-04-19 11:11:50.378174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f2581af324'
down_revision: Union[str, None] = 'f09dfb4ab21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_for_customer', sa.Column('order_detail', sa.ARRAY(sa.Integer()), nullable=False))
    op.create_unique_constraint(op.f('uq_invoice_for_customer_order_detail'), 'invoice_for_customer', ['order_detail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_invoice_for_customer_order_detail'), 'invoice_for_customer', type_='unique')
    op.drop_column('invoice_for_customer', 'order_detail')
    # ### end Alembic commands ###
