"""Update constrain field contract_for_vendor.

Revision ID: ab8bda6152f1
Revises: d42d7bb0426e
Create Date: 2024-04-03 15:33:36.332651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8bda6152f1'
down_revision: Union[str, None] = 'd42d7bb0426e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_contract_vendor', 'contract_for_vendor', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_contract_vendor', 'contract_for_vendor', 'vendor', ['belong_to_vendor'], ['vendor_name'])
    # ### end Alembic commands ###
