"""update (order detail in invoice).

Revision ID: abd04262fe37
Revises: def0c1b9b0c3
Create Date: 2024-04-19 11:09:25.756453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd04262fe37'
down_revision: Union[str, None] = 'def0c1b9b0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_invoice_for_customer_order_detail'), 'invoice_for_customer', ['order_detail'])
    op.add_column('product', sa.Column('branch', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'branch')
    op.drop_constraint(op.f('uq_invoice_for_customer_order_detail'), 'invoice_for_customer', type_='unique')
    # ### end Alembic commands ###
