"""create product column in batch table

Revision ID: aec69d02ff61
Revises: e031add93238
Create Date: 2024-04-11 23:43:24.870637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec69d02ff61'
down_revision: Union[str, None] = 'e031add93238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('product_id', sa.String(), nullable=False))
    op.create_foreign_key(op.f('fk_batch_product_id_product'), 'batch', 'product', ['product_id'], ['id'])
    op.drop_index('ix_product_batch_id', table_name='product')
    op.drop_constraint('fk_product_batch', 'product', type_='foreignkey')
    op.drop_column('product', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
