"""change belong_to_contract in ImportOrder nullable

Revision ID: af1c3d99a374
Revises: 08f1f89cf696
Create Date: 2024-04-19 22:31:12.097010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1c3d99a374'
down_revision: Union[str, None] = '08f1f89cf696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=False),
    sa.Column('import_price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_detail'))
    )
    op.create_index(op.f('ix_import_detail_id'), 'import_detail', ['id'], unique=False)
    op.alter_column('import_order', 'belong_to_contract',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_order', 'belong_to_contract',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.drop_index(op.f('ix_import_detail_id'), table_name='import_detail')
    op.drop_table('import_detail')
    # ### end Alembic commands ###
