"""Modify field full_name employee constrain.

Revision ID: b0c55751f665
Revises: 2f94580ddb6a
Create Date: 2024-03-30 10:08:56.595047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c55751f665'
down_revision: Union[str, None] = '2f94580ddb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_full_name', 'employee', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_employee_full_name', 'employee', ['full_name'])
    # ### end Alembic commands ###
