"""create branch  column in ContractForVendor

Revision ID: b0e1f704eaaa
Revises: 2dae1cc6c7d1
Create Date: 2024-04-21 01:39:10.109494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e1f704eaaa'
down_revision: Union[str, None] = '2dae1cc6c7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_for_vendor', sa.Column('branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_for_vendor', 'branch')
    # ### end Alembic commands ###
