"""Delete password column in employee

Revision ID: b22973112e0a
Revises: d06e43d62a38
Create Date: 2024-04-11 16:35:06.244526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b22973112e0a'
down_revision: Union[str, None] = 'd06e43d62a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch_employees')
    op.drop_column('employee', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
