"""create belong_to_order column

Revision ID: b3f32834850f
Revises: 4968a695743f
Create Date: 2024-04-16 13:34:28.031662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f32834850f'
down_revision: Union[str, None] = '4968a695743f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_for_customer', sa.Column('belong_to_order', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_invoice_for_customer_belong_to_order'), 'invoice_for_customer', ['belong_to_order'])
    op.create_foreign_key(op.f('fk_invoice_for_customer_belong_to_order_purchase_order'), 'invoice_for_customer', 'purchase_order', ['belong_to_order'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invoice_for_customer_belong_to_order_purchase_order'), 'invoice_for_customer', type_='foreignkey')
    op.drop_constraint(op.f('uq_invoice_for_customer_belong_to_order'), 'invoice_for_customer', type_='unique')
    op.drop_column('invoice_for_customer', 'belong_to_order')
    # ### end Alembic commands ###
