"""change order_detail type

Revision ID: b66796fe7867
Revises: 294827de8bfc
Create Date: 2024-04-16 22:15:44.607408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b66796fe7867'
down_revision: Union[str, None] = '294827de8bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoice_for_customer_order_detail', 'invoice_for_customer', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_invoice_for_customer_order_detail', 'invoice_for_customer', ['order_detail'])
    # ### end Alembic commands ###
