"""Add field password to employee.

Revision ID: b7df54c04789
Revises: e28bcd304a77
Create Date: 2024-04-02 10:39:23.705789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7df54c04789'
down_revision: Union[str, None] = 'e28bcd304a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'password')
    # ### end Alembic commands ###
