"""Remove column of categories table

Revision ID: b98e86359b16
Revises: 92fa086951a7
Create Date: 2024-02-29 21:19:19.817081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98e86359b16'
down_revision: Union[str, None] = '92fa086951a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'has_promotion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('has_promotion', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
