"""Add column to tenant table.

Revision ID: be640ea7f9a6
Revises: 99bad9cc11c2
Create Date: 2024-04-17 14:36:03.018626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be640ea7f9a6'
down_revision: Union[str, None] = '99bad9cc11c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
