"""Set TZ to VN.

Revision ID: c0623b26bd3c
Revises: 3ba3c3cb447c
Create Date: 2024-04-10 20:41:59.653497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0623b26bd3c'
down_revision: Union[str, None] = '3ba3c3cb447c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_from_vendor', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('invoice_from_vendor', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('order_of_batch', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('order_of_batch', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product_of_import_order', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('product_of_import_order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('promotion', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('promotion', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('promotion_belong_to_branch', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('promotion_belong_to_branch', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('promotion_for_order', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('promotion_for_order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_for_order', 'updated_at')
    op.drop_column('promotion_for_order', 'created_at')
    op.drop_column('promotion_belong_to_branch', 'updated_at')
    op.drop_column('promotion_belong_to_branch', 'created_at')
    op.drop_column('promotion', 'updated_at')
    op.drop_column('promotion', 'created_at')
    op.drop_column('product_of_import_order', 'updated_at')
    op.drop_column('product_of_import_order', 'created_at')
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.drop_column('order_of_batch', 'updated_at')
    op.drop_column('order_of_batch', 'created_at')
    op.drop_column('invoice_from_vendor', 'updated_at')
    op.drop_column('invoice_from_vendor', 'created_at')
    # ### end Alembic commands ###
