"""Delete FK of Contract table

Revision ID: c6cf12d917d7
Revises: 2eaabc8004f9
Create Date: 2024-03-01 11:40:41.588241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6cf12d917d7'
down_revision: Union[str, None] = '2eaabc8004f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contract_belong_to_vendor_fkey', 'contract', type_='foreignkey')
    op.drop_column('contract', 'belong_to_vendor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('belong_to_vendor', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('contract_belong_to_vendor_fkey', 'contract', 'vendor', ['belong_to_vendor'], ['id'])
    # ### end Alembic commands ###
