"""add created_at, updated_at to order table

Revision ID: cdc626898e1c
Revises: 6fcc1ad4f79f
Create Date: 2024-04-26 23:28:16.514135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc626898e1c'
down_revision: Union[str, None] = '6fcc1ad4f79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Ho_Chi_Minh', now())"), nullable=True))
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'created_at')
    # ### end Alembic commands ###
