"""add img_url to product table

Revision ID: d05f03033f0d
Revises: 33c2421e7eb4
Create Date: 2024-05-02 14:23:16.297594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05f03033f0d'
down_revision: Union[str, None] = '33c2421e7eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'img_url')
    # ### end Alembic commands ###
