"""delete belong_in_invoice in ImportOrder table

Revision ID: d0a12ece1866
Revises: dd68705365c4
Create Date: 2024-04-19 19:34:25.223643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a12ece1866'
down_revision: Union[str, None] = 'dd68705365c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_import_order_invoice_from_vendor', 'import_order', type_='foreignkey')
    op.drop_column('import_order', 'belong_to_invoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_order', sa.Column('belong_to_invoice', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_import_order_invoice_from_vendor', 'import_order', 'invoice_from_vendor', ['belong_to_invoice'], ['id'])
    # ### end Alembic commands ###
