"""Change type barcode to not unique

Revision ID: d34c0bb0519a
Revises: cdc626898e1c
Create Date: 2024-04-29 20:36:53.557612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34c0bb0519a'
down_revision: Union[str, None] = 'cdc626898e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_barcode', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_barcode', 'product', ['barcode'])
    # ### end Alembic commands ###
