"""Add column of model employee

Revision ID: d4662e5ce4e5
Revises: 4c8633fd6ad5
Create Date: 2024-02-29 19:13:42.049457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4662e5ce4e5'
down_revision: Union[str, None] = '4c8633fd6ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('branch_name', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'employee', 'branch', ['branch_name'], ['name_detail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'branch_name')
    # ### end Alembic commands ###
