"""change length string for role column in employee table

Revision ID: d7fb39555ae7
Revises: 71c6f9178ade
Create Date: 2024-03-09 19:31:35.610662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fb39555ae7'
down_revision: Union[str, None] = '71c6f9178ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'role',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.create_foreign_key('fk_invoice_from_vendor', 'invoice_from_vendor', 'vendor', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
