"""Add expiry_date column in ImportDetail

Revision ID: da9e5f7d1e67
Revises: 1faf9a0b0ab8
Create Date: 2024-04-24 20:14:58.825608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9e5f7d1e67'
down_revision: Union[str, None] = '1faf9a0b0ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_detail', sa.Column('expiry_date', sa.Date(), nullable=True))
    # op.drop_column('noti', 'tenant_id')
    # op.drop_column('noti', 'branch')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('noti', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('noti', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('import_detail', 'expiry_date')
    # ### end Alembic commands ###
