"""Add product_name column in info table

Revision ID: de9100515200
Revises: dfa0c459df8b
Create Date: 2024-06-01 16:07:09.068131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9100515200'
down_revision: Union[str, None] = 'dfa0c459df8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('product_id', sa.String(), nullable=False))
    op.add_column('info', sa.Column('product_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'product_name')
    op.drop_column('info', 'product_id')
    # ### end Alembic commands ###
