"""add manager_name column in employee table

Revision ID: e0398207ce57
Revises: 0bafdf4c4a47
Create Date: 2024-03-10 12:12:25.719913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0398207ce57'
down_revision: Union[str, None] = '0bafdf4c4a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('manager_name', sa.String(length=255), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'manager_name')
    # ### end Alembic commands ###
