"""drop (order detail in invoice).

Revision ID: f09dfb4ab21c
Revises: abd04262fe37
Create Date: 2024-04-19 11:11:06.522142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09dfb4ab21c'
down_revision: Union[str, None] = 'abd04262fe37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoice_for_customer_order_detail', 'invoice_for_customer', type_='unique')
    op.drop_column('invoice_for_customer', 'order_detail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_for_customer', sa.Column('order_detail', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_invoice_for_customer_order_detail', 'invoice_for_customer', ['order_detail'])
    # ### end Alembic commands ###
