"""drop table branch_employee.

Revision ID: f351efe01652
Revises: 9d28a8f0ded9
Create Date: 2024-04-17 16:29:19.089450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f351efe01652'
down_revision: Union[str, None] = '9d28a8f0ded9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch_employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name='fk_branch_employees_branch_id_branch'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_branch_employees_employee_id_employee'),
    sa.PrimaryKeyConstraint('id', name='pk_branch_employees')
    )
    # ### end Alembic commands ###
