"""create FK categories in product table

Revision ID: f49c6eb2f23e
Revises: 150098dddaec
Create Date: 2024-03-22 13:32:17.802133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f49c6eb2f23e'
down_revision: Union[str, None] = '150098dddaec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('categories_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_product_categories_id'), 'product', ['categories_id'], unique=False)
    op.create_foreign_key(op.f('fk_product_categories_id_categories'), 'product', 'categories', ['categories_id'], ['id'])
    op.drop_column('product', 'categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
