"""add column branch to purchase order

Revision ID: f61cf3a976fa
Revises: 55a65c96f485
Create Date: 2024-04-20 10:10:24.128228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61cf3a976fa'
down_revision: Union[str, None] = '55a65c96f485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('branch', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'branch')
    # ### end Alembic commands ###
