"""Update constrain field vendor.

Revision ID: fc21d6979993
Revises: 6c838ea9ab1a
Create Date: 2024-04-03 15:53:38.799546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc21d6979993'
down_revision: Union[str, None] = '6c838ea9ab1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_constraint('uq_vendor_vendor_name', 'vendor', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vendor_vendor_name', 'vendor', ['vendor_name'])
    op.alter_column('vendor', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('vendor', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
