"""Create new column in OrderDetail.

Revision ID: fe66f9a9cfcc
Revises: 28707f337038
Create Date: 2024-04-13 12:12:28.056029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe66f9a9cfcc'
down_revision: Union[str, None] = '28707f337038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_id', sa.String(), nullable=True))
    op.add_column('order', sa.Column('product_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'product_name')
    op.drop_column('order', 'product_id')
    # ### end Alembic commands ###
